### ISSUE TITLE
Checklist for releasing a version of xray with dask support

### ISSUE THREAD

**Issue by shoyer** [xray/xray#394]
For dask:

- [x] [default threadpool](https://github.com/ContinuumIO/dask/issues/154) for dask.array
- [x] fix [indexing bugs](https://github.com/ContinuumIO/dask/pull/149) for dask.array
- [x] make a decision on (and if necessary implement) [renaming "block" to "chunk"](https://github.com/ContinuumIO/dask/issues/150)
- [x] fix [repeated use of `da.insert`](https://github.com/ContinuumIO/dask/pull/165)

For xray:

- [x] update xray for the updated dask (https://github.com/xray/xray/pull/395)
- [x] figure out how to handle caching with the `.load()` method on dask arrays
- [x] cleanup the xray documentation on dask array.
- [x] write an introductory blog post

Things we can add in an incremental release:

- make [non-aggregating grouped operations more useable](https://github.com/xray/xray/issues/392)
- automatic [lazy apply](https://github.com/ContinuumIO/dask/pull/122) for grouped operations on xray objects

CC @mrocklin

**Comment by mrocklin** [comment]
What is your ideal timeline on this?

**Comment by shoyer** [comment]
No particular rush :). Maybe the next week or two?

**Comment by shoyer** [comment]
v0.5 is out!

The blog post should be published on Thursday.
